name: "refonte IAC"
on:
  push:
    branches:
      - main
      - staging
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
env:
    # This is the environment variable for the AWS credentials
    # that will be used in the workflow.
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    #s3 bucket  for terraform state
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
    AWS_REGION: us-east-1

jobs:
  terraform:
    name: "apply terraform code changes"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        #with:
        #  terraform_version: 1.6.3

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out tfplan
        continue-on-error: true
        # This will allow the workflow to continue even if the plan fails.

      - name: Terraform Plan status

        id: plan_status
        run: |
          if [ "${{ steps.plan.outcome }}" == "failure" ]; then
            echo "Terraform plan failed. Please check the logs."
            exit 1
          fi

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && steps.event_name == 'push'
        run: terraform apply -auto-approve -input=false - parallelism=1 -no-color -input=false tfplan

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kube config file
        id: getkubeconfig
        if: steps
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
        continue-on-error: true
           
      - name: Install Ingress controller
        if: steps.apply.outcome == 'success' && steps.getkubeconfig.outcome == 'success'
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          kubectl wait --namespace ingress-nginx --for=condition=ready pod --all --timeout=90s
          kubectl get pods -n ingress-nginx -o wide
          kubectl get svc -n ingress-nginx -o wide